### PR TITLE
Testing pupil daq

### PR DESCRIPTION
**Pull request by genagain**
This is the inital test suite with Unittest. I experimented with Mocking quite a bit. In my experience the EventDetector class couldn't even be initiated, without the Pupil, so I couldn't really mock anything.

### CODE REVIEW

**Comment by jczeck** [comment]
2 things,
What is with putting event detector in it's own folder? Also, that is an old version of the code.
Also, for mocking did you look at patch? It's a way to say this function does this.

**Comment by genagain** [comment]
The EventDectector is in its own folder so it can be imported into the test as a module. I did look into patching but didn't have much success. As for the old version of the code I pulled master and merged in to this branch and nothing changed. We can merge the newer branch before this one and I can resolve merge conflicts.

**Comment by genagain** [comment]
The EventDectector is in it's own folder so it can be imported into the test as a module. I did look into patching but didn't have much success. 

Computer Engineering Student, Class of 2017
Northeastern University
(347) 986-0720

**Comment by genagain** [comment]
As for the old version of the code I pulled master and merged in to this branch and nothing changed. We can merge the newer branch before this one and I can resolve merge conflicts. 

Computer Engineering Student, Class of 2017
Northeastern University
(347) 986-0720

**Comment by genagain** [comment]
I created a new pull request for the testing stuff, so I'm closing this one.

**Pull request closed without merging**
